### PR TITLE
Tutorials ported to ROS 2

### PR DESCRIPTION
**Pull request by hello-chintan**
The tutorial package has been ROSified and ported to ROS 2 Galactic. The scripts have been tested to work on 1002. Request you to test on 1005 as well before approving and merging the PR.

Pending work: the tutorial instructions are yet to be updated to run the scripts with ROS 2, expect this to be done soon!

### CODE REVIEW

**Review by hello-sanchez — COMMENTED** [review]
multipoint_command.py has self.subscription repeated in the __init__ method of the class. Its in line 34.  Same thing can be said for the stow_command.py node. Also, is it possible to automatically exit out of the nodes once they execute the joint trajectory goal?

**Comment by hello-chintan** [comment]
Thanks for the review! Odd as it may seem, self.subscription is repeated to suppress the 'unused variable' warning. It's of little consequence but it's a convention that they are recommending in the official ROS 2 tutorials. Best to keep with it.

As for exiting out of the node after execution, do you mean not having to Ctrl+C to return control of the terminal back to the user once the trajectory is executed?

**Comment by hello-sanchez** [comment]
Ahh, that's interesting. Does that mean we need self.subscription repeated in each node? 

Yes, return control of the terminal back to the user once the trajectory is executed. Is that possible?

**Comment by hello-chintan** [comment]
Yup, in every node that has a subscriber we could have the instance repeated.

Of course, returning control to the terminal is doable. Currently, the spin() method on line 126 is calling the executor to call the joint_states subscriber repeatedly which is blocking code. If we want to return control back to the user, we could either spin for limited iterations or have a stopping condition for spinning the node, which could be when the trajectory is done executing. 

In my opinion, we could as well keep the node running so that users have the opportunity to inspect the node elements through ROS CLI. Let me know if you have a different idea.

**Comment by hello-chintan** [comment]
Raising this PR on Hello Robot's Github repo and closing this one.

**Pull request closed without merging**
